# Generated by Django 4.1.7 on 2023-06-28 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
                ('shift', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('faculty_id', models.CharField(max_length=20, unique=True)),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default=' ', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrolment_no', models.CharField(max_length=20)),
                ('class_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='ams.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.faculty'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[(None, 'Not marked'), ('Present', 'Present'), ('Absent', 'Absent')], default=None, max_length=10, null=True)),
                ('class_attendance', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ams.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.student')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
