# Generated by Django 3.1.7 on 2023-07-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_faculty_faculty_image_alter_faculty_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='post',
            field=models.CharField(choices=[('HOD', 'hod'), ('Associate Professor', 'associate professor'), ('Assistant Professor', 'assistent professor')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
