# Generated by Django 3.1.7 on 2023-08-08 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_auto_20230808_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ams.faculty'),
        ),
        migrations.AlterField(
            model_name='class',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_classes', to='ams.faculty'),
        ),
    ]
