# Generated by Django 3.1.7 on 2023-07-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_auto_20230725_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='post',
        ),
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_Post',
            field=models.CharField(blank=True, choices=[('Hod', 'Hod'), ('Associate Professor', 'Associate professor'), ('Assistant Professor', 'Assistent professor')], default=None, max_length=50),
        ),
    ]
