# Generated by Django 4.1.7 on 2023-08-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0004_alter_b_com_attendance_id_alter_b_com_student_id_and_more'),
        ('ams', '0004_auto_20230808_2246'),
    ]

    operations = [
    ]
