# Generated by Django 3.1.7 on 2023-07-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0004_auto_20230725_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='qualifications',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
