# Generated by Django 3.1.7 on 2023-07-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_faculty_qualifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='faculty_Post',
            new_name='Designation',
        ),
    ]
