# Generated by Django 4.1.7 on 2023-08-10 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_merge_20230808_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subject', to='ams.class')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='ams.faculty')),
            ],
        ),
    ]
