# Generated by Django 3.1.7 on 2023-07-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0006_auto_20230729_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Email',
            field=models.EmailField(blank=True, default=None, max_length=50),
        ),
    ]
