# Generated by Django 3.1.7 on 2023-08-10 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0008_auto_20230810_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='bca_attendance',
            name='subject_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams.subject'),
        ),
    ]
