# Generated by Django 3.1.7 on 2023-08-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0010_auto_20230801_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Designation',
            field=models.CharField(blank=True, choices=[('Associate Professor,Head ', 'Associate Professor,Head'), ('Assistant Professor,Head', 'Assistant Professor,Head'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor')], default=None, max_length=50),
        ),
    ]
