# Generated by Django 4.1.7 on 2023-08-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0011_auto_20230801_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='role',
            field=models.CharField(blank=True, choices=[('Head Of Department(HOD)', 'Head Of Department(HOD)'), ('(Class Coordinator)', '(Class Coordinator)'), ('(Subject Teacher)', '(Subject Teacher)')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
