# Generated by Django 3.1.7 on 2023-08-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0011_bba_attendance_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_ed_attendance',
            name='subject_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams.subject'),
        ),
    ]
