# Generated by Django 3.1.7 on 2023-08-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0013_auto_20230805_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='role',
            field=models.CharField(blank=True, choices=[('Head Of Department(HOD)', 'Head Of Department(HOD)'), ('Class Coordinator', 'Class Coordinator'), ('Subject Teacher', 'Subject Teacher')], default=None, max_length=50),
        ),
    ]
