# Generated by Django 3.1.7 on 2023-08-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0014_auto_20230806_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='Bca_Attendance',
        ),
    ]
