# Generated by Django 3.1.7 on 2023-08-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0015_law_attendance_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=25),
        ),
    ]
