# Generated by Django 3.1.7 on 2023-08-06 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0015_auto_20230806_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='Bca_Student',
        ),
    ]