# Generated by Django 3.1.7 on 2023-08-06 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0018_bba_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bba_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[(None, 'Not marked'), ('Present', 'Present'), ('Absent', 'Absent')], default=None, max_length=10, null=True)),
                ('class_attendance', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ams.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.bba_student')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
