# Generated by Django 3.1.7 on 2023-08-06 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0019_bba_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='B_Ed_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrolment_no', models.CharField(max_length=20)),
                ('class_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='B_Ed_students', to='ams.class')),
            ],
            options={
                'ordering': ['enrolment_no'],
            },
        ),
    ]
