# Generated by Django 3.1.7 on 2023-08-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0022_b_com_attendance_b_com_student_law_attendance_law_student_mba_attendance_mba_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bca_student',
            name='class_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='ams.class'),
        ),
    ]
