# Generated by Django 3.1.7 on 2023-08-06 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0023_auto_20230806_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bca_student',
            name='class_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bca_students', to='ams.class'),
        ),
    ]
